### ISSUE TITLE
Discuss preliminary findings with other organisations doing OD measurements

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1032]
Other organisations that are part of the Measurement and Accountability Working Group assess open data too.

Some of them focus on some index metrics - e.g. the Center of Open Data Enterprise assesses accessibility and findability.

Once we have preliminary findings we can share them with these orgs. Ideally we get input, how to improve our assessment, and can deliver interesting insights for other orgs

These orgs can also spread the findings to their audiences.

**Comment by morchickit** [comment]
@dannylammerhirt to create an email template to send to MAWG and other partners (GODAN, NDI, CADASTA)

**Comment by morchickit** [comment]
@dannylammerhirt I created a template to share with other orgs: https://docs.google.com/document/d/1A66Mz10XGK5lEeBnl-6AUOH3aRY7Ky8cxEGtWQ1tluw/edit

This is different than what you suggested originally because it is to help us to test the site before launch, but we can build on that to help us spread the findings etc. 

Please give feedback ASAP so we can divide the work of who send an email to who.

**Comment by morchickit** [comment]
@dannylammerhirt - this was sent by me to the Web Foundation. Please specify who else we need to send it to. I dont think we need to share it with too many people before the launch, we can always do personal outreach the week after the launch as well.

**Comment by dannylammerhirt** [comment]
Legislative data: Greg Brown National Democratic Institute; 
Election data: Michael McNulty, Michelle Brown National Democratic Institute; 
Land ownership data: Frank Pichel, Lindsay Ferris Cadasta Foundation; 
Weather forecast data: Ben Schaap Global Open Data for Agriculture and Nutrition

**Comment by morchickit** [comment]
Sent!
