### ISSUE TITLE
In local census, q. 8 doesn't allow comment only

### ISSUE THREAD

**Issue by tlacoyodefrijol** [okfn/opendatasurvey#867]
In q.8, when no format is selected, census says the question is required. This happens only in local census instances. 
![screen shot 2016-12-22 at 11 34 37 am](https://cloud.githubusercontent.com/assets/5587545/21435486/d04cf412-c83f-11e6-8d8a-30eb33a7ade7.png)

**Comment by morchickit** [comment]
@tlacoyodefrijol - please also write about it in the forum (if it's not alredy there)

**Comment by morchickit** [comment]
@brew - this now really interrupt the Brazil local census. How can we solve it? 

See the email we got from them:
"Dear Oscar and Mor,
 
I’m also ccing Ariel Kogan here and the rest of our team at FGV/DAPP.
 
I wanted to point out a urgent issue for the release of the Local ODI for Brazilian cities. You might remember an issue we had before we submitted the datasets about open format. In the global survey (countries), question B8 allowed to have no answer, which would mean, for the methodology, that there’s no open format (machine-readable) available, which is the case when only PDF formats are available, for example. But for the Local index, I was not allowed to let this question blank.
 
I reported this, but you instructed us to change the spreadsheet in order to incorporate the formats like PDF in the list of possible formats. Although it didn’t match the methodology, I did it in order to submit datasets. But the index calculation considered, for all the datasets available only in PDF, that the dataset was in open format, which is not true. As a result, we have a biased evaluation for cities, because every dataset is being considered as available in open format because B8 can’t be answered with just “nothing”.
 
For Rio de Janeiro, 4 datasets had this problem: water quality, government budget, city laws and procurement. For São Paulo, 2 datasets: company register and water quality.
 
We didn’t identify this problem in time for the release of the São Paulo index, but since this is a major issue (it touches directly one of the main criteria evaluated: the format), I think it is very urgent that this is changed at least for the release of the Rio de Janeiro index. In other words, B8 should allow the answer to be just “nothing” and evaluate that dataset as “not having open format data”.
 
We are closing the content of the report between today and tomorrow, in order to be available for the event next week. Could you please provide a solution for this question as soon as possible?
 
Thanks a lot for your attention. I keep at your disposal if anything is still unclear.
 
Best regards,
Wagner

**Comment by brew** [comment]
In the config for the Brazil survey, in the QuestionSet tab, the json snippet for `question_set_schema`, the `required` property for the `format` question has been set to `true`. Set this to `false` to make the question not required.

**Comment by brew** [comment]
This question has been reset to `required: false` for all local surveys (the default).
