### ISSUE TITLE
Analyse Sample and write about it

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#884]
For the launch site - why we have the sample we have? What does it mean? What we need to do to improve it?

See Oscar's draft text here: https://docs.google.com/document/d/193XH1xiWOtN97bdWmkke0AJDyjH2h6KcfLvXIvauDPo/edit#heading=h.pfo43flb788s

**Comment by tlacoyodefrijol** [comment]
Do you mean the countries sample? Improve as in having more countries in the Index?

**Comment by morchickit** [comment]
That's right. Maybe how can we make the index more diverse in geographical
reach

**Comment by dannylammerhirt** [comment]
@morchickit and @tlacoyodefrijol what sample are you talking about? Do you mean the full list of countries we are covering in the 2016 edition? 

As I understood this is mainly a matter of capacity building of submitters in regions. The Web Foundation, @KateRogers and I were sitting together in order to discuss how we can get more submitters in countries that we don't cover. I link our working document in here: https://docs.google.com/document/d/1ymauCfBqy-Nc-jpU9bZ2MK0kffBMbb_06RW5ewjf88Q/edit#

Increasing the geographical scope of GODI is good. Yet, we need to make sure to cover the countries the Web Foundation is intending to cover in their 2017 edition. 

See the ODB country list here: https://docs.google.com/spreadsheets/d/1SNkyRJegWrqi7Z83UyzvF36NaHJLgTQG2C_gEbNle9M/edit#gid=1350212251

**Comment by morchickit** [comment]
This analysis should take the ODB into consideration, but more to be about
the current survey. It also, when looking at the OK network, reflect some
of our network problem, and this is why Oscar is also on this issue. There
is a need here to a written delivery such as a blog post or a paper.

**Comment by KateRogers** [comment]
Opportunity to work with the WF on a public facing assessment on where we are both  struggling to find local expertise (SE asia, for example)

**Comment by morchickit** [comment]
@tlacoyodefrijol to lead the writing on this @dannylammerhirt to assist

**Comment by dannylammerhirt** [comment]
This spreadsheet contains stats on submitters: https://docs.google.com/spreadsheets/d/1sXqJwzAVMpqyorqbcd8tHx-Qw8Y-wNRX9RpuuT1tbR8/edit#gid=2126165848

**Comment by dannylammerhirt** [comment]
Current file to work in:
https://docs.google.com/document/d/1uulHJLKAVLwZzLIs-rGE3ZdqPUM1P8V3Y5u9hZ2eXho/edit

Older version: https://docs.google.com/document/d/193XH1xiWOtN97bdWmkke0AJDyjH2h6KcfLvXIvauDPo/edit

**Comment by dannylammerhirt** [comment]
@tlacoyodefrijol to finish the post by Monday

**Comment by morchickit** [comment]
@tlacoyodefrijol - are you working on the link that is under the older version?

**Comment by dannylammerhirt** [comment]
@morchickit I changed it: we are working in the "latest version"

**Comment by tlacoyodefrijol** [comment]
Final draft is here https://docs.google.com/document/d/1uulHJLKAVLwZzLIs-rGE3ZdqPUM1P8V3Y5u9hZ2eXho/edit#
any last comments?
@morchickit @dannylammerhirt

**Comment by morchickit** [comment]
Great stuff @tlacoyodefrijol !

I added a couple of last comments. Can you add it to the CMS? We can publish this on Wednesday!
