### ISSUE TITLE
Write GODI report with main findings

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#904]
We need to write a final report to justify what we did to achieve the outlined goals. 

Final report https://docs.google.com/document/d/1p38Y46tVxbP0TLFLAfv8qDdW2M1tqwiXR6SW-8kGJi4/edit#

Outtakes (contains relevant information):
https://docs.google.com/document/d/1uNAln9QxLsOKoLv0SrU-OT2xfT1hXDQVD22V-YN15ss/edit

Folder with all relevant files here: https://drive.google.com/drive/folders/0B5j55T4ZyssBTlhsZEMzN2NJdU0

Raw data for "GODI RESULTS" section are here: https://docs.google.com/spreadsheets/d/17zmn4wgxPaJozY9EjETjoL4ZVsV_T4wu5EYBT4B5MHY/edit#gid=560413061

**Comment by dannylammerhirt** [comment]
@morchickit what do you mean by "sample"?

**Comment by dannylammerhirt** [comment]
@morchickit  is this the grant report?

**Comment by morchickit** [comment]
No, final report for the index. Not for the grant.

**Comment by dannylammerhirt** [comment]
The data characteristics document can be found at: https://github.com/okfn/opendatasurvey/issues/905

The data characteristics are our unit of analysis. In theory all survey questions need to apply to the entire list of characteristics. Weather forecasts should be open for various types of forecasts. 

Problem: 
Government publishes data in different files. One file is open, but does not have relevant granularity (does not meet all characteristics). Another file is closed, but contains relevant information. Reviewers find different datasets, some are openly licensed, others are not. Only some are in machine-readable formats. What should they do?  A systematic approach is needed how we select our unit of analysis from different datasets.

Solution: In these cases the review can be based on **two approaches**

1) reviewers use a reference dataset that contains all relevant characteristics and answer questions B2 and B4 until B8 (B9 should be commented on) with reference to this dataset. The main point is that the dataset contains all data characteristics. If reviewers have to choose between two or more similar datasets, choose the one that is most applicable to the questions B2, B4-B8. They document their choice in the comment section. In case that something is unclear, reviewers consult the forum. 

2) reviewers cannot find a reference dataset, because the data is split into various datasets. In this case, they refer questions B2 and B4-B8 to all datasets. GODI assumes that these datasets are representative for the data characteristics and in the end we want to assess how open this key information is. Example: If one dataset displays votes on bills and is openly licensed, but another one contains transcripts of debates in parliament and is not openly licensed, then the answer to question B7 would be "No".

**Comment by dannylammerhirt** [comment]
Find draft outline here (in progress): 

https://docs.google.com/document/d/1p38Y46tVxbP0TLFLAfv8qDdW2M1tqwiXR6SW-8kGJi4/edit

**Comment by dannylammerhirt** [comment]
Add a section on how to read our results. This is necessary so people understand our icons and can better interpret how they **relate** to one another. Prior discussions on the forum show, that people see logical links between our questions, where there are none, necessarily. For example some question how data can be in bulk if it is outdated. The assumption is that bulk should cover a longer time span of data - but this is not the case

**Comment by dannylammerhirt** [comment]
https://waffle.io/okfn/opendatasurvey/cards/5891ca022e70b12701f57827

**Comment by dannylammerhirt** [comment]
Analyse if/how our new scoring influenced the ranking of the top 10 countries

**Comment by dannylammerhirt** [comment]
Analysis of findability: 

- [ ] check how many URLs were changed by reviewers
- [ ] check how submitters looked for data: did they say "Yes, data was totally easy to find", but did not tick all data characteristics

**Comment by dannylammerhirt** [comment]
**Country ranking**
- [ ] Analysis sheet of changes of country rankings between 2015 and 2016
 - [ ] Create a comparative list (here: https://docs.google.com/spreadsheets/d/1AEFFec45U7FcuyVnW-i7VyXp3tI6pe5p1Tzt72LnMm4/edit#gid=1664837800)
 - [ ] Add metadata explaining methodology into the xls sheet 
 - [ ] Visualize the ranking changes
- [ ] Write short post: research questions, analysis, findings (https://docs.google.com/document/d/1bhWM37LZXQDSqcpaTQ2cYn3M5nSA7RCHoiYWzZQhoDM/edit)

**URL analysis**
- [ ] Retrieve all URLs where our submitters found data
- [ ] remove countries that are not included in two or more year (check if you do two-year comparison or four year comparison)
- [ ] only leave in URLs from data categories that are similar over time
- [ ] shorten URLs with DMI Harvester tool to only return host names (Purpose: URLs to single pages on host may change. More interesting is whether we assess different hosts (e.g. institutional websites, or data catalogues?) Tool: https://wiki.digitalmethods.net/Dmi/ToolHarvester 
- [ ] Analyse how many data.gov. or data.gob we find 
- [ ] Research question: does our reference point change? Do people refer to different URLs over time? 
- [ ] over time there should be a movement away from institutional website to data catalogue (promise of increased findability). Can we observe this? 
- [ ] Caveat: we do not always collect URLs (in cases where we rejected submissions this year)

**Comment by morchickit** [comment]
@tlacoyodefrijol we need this for next week! Deadline is Tuesday

**Comment by dannylammerhirt** [comment]
- insert all ideas for future research to https://waffle.io/okfn/opendatasurvey/cards/58e60f0ff0f6b1a5001cf9b4

**Comment by StephenAbbott** [comment]
[FinalreportTheStateofOpenGovernmentDatain2017.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57876299f2679f0e00d2416f/125516c66e82c728ace21e0d46ce9d94228e91ac9fe6ad579055f5a73d47337626028c3b758bc427a947690f020a10e835091b15a5a78b2ba7b12e6c981c49b28b380c30d43703a9bf8a18bc57b9738c1cd0e2e9894fc2e83d73e08a86483d0c190acbae0361ffc412820db459eb5f56a6193767ef713578409c19752a6e6534e6.pdf)
