### ISSUE TITLE
If the format in question B8 is HTML we need to give a score of 0

### ISSUE THREAD

**Issue by tlacoyodefrijol** [okfn/opendatasurvey#935]

**Comment by brew** [comment]
Suggest removing HTML from format list.

**Comment by brew** [comment]
HTML has been removed from the list of valid options for the format question. If a dataset entry used HTML as their only option, the format question will now not be considered 'open'. E.g. http://global.survey.okfn.org/entry/af/procurement/ the answer for format is HTML (because that was what was entered at the time), but because it's not on the list of valid options, no score is given for the question.
